server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: unbound-dns
  static_configs:
  - targets:
      - localhost
    labels:
      job: unbound-dns
      __path__: /var/log/unbound/unbound.log
