---
name: CI pipeline for unbound-dns project

on:
  push:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Copy reppo
        uses: actions/checkout@v4

      - name: Login dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/image-unbound-dns:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run container
        run: docker run -d -p 9080:9080 -p 5335:53 -p 3100:3100 --name container-unbound-dns ${{ secrets.DOCKERHUB_USERNAME }}/image-unbound-dns:latest

      - name: Install python requirements
        run: pip install -r tests/test_requirements.txt

      - name: Run Promtail tests
        run: pytest tests/test_promtail.py

      - name: Run Loki tests
        run: pytest tests/test_loki.py

      - name: Run DNS tests
        run: pytest tests/test_dns.py

      - name: Remove container
        run: docker rm -f container-unbound-dns

      - name: Push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/image-unbound-dns:latest
